#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-moses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-moses
  template:
    metadata:
      labels:
        app: prod-stedi-moses
    spec:
      containers:
        - name: prod-stedi-moses
          image: us-docker.pkg.dev/unstable-unicorns-389016/moses-stedi-api/stedi-api:latest #This need to be change to the new one that need to be created
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-prod
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-prod" #this will change
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-moses-nodeport
spec:
  selector:
    app: prod-stedi-moses
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-stedi-moses-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sprod-stedi-moses-public #this ip need to create first
    networking.gke.io/managed-certificates: prod-stedi-moses-certificate
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-moses-nodeport # this need to match line 53
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-moses-certificate #this need to match line 68
spec:
  domains:
    - moses.cit262.com #this is a DNS record that has not been created yet
    
